version: '3.8'
services:
  mongodb:
    image: mongo:latest # use the latest image
    container_name: mongodb
    restart: unless-stopped
    environment: # set required env variables to access mongo
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes: # optional to preserve database after container is deleted
      - ./database-data:/data/db
      - /etc/timezone:/ect/timezone:ro

  mongo-express:
    image: mongo-express
    container_name: mongo_ui
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_USER: trungnguyen
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: order-service
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  my-db:
