server:
  port: 0

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      port: 27017
      username: trungnguyen
      password: password
      authentication-database: admin
      database: product-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka