server:
  port: 8080

spring:
  application:
    name: product
  data:
    mongodb:
      host: localhost
      port: 27017
      username: trungnguyen
      password: password
      authentication-database: admin
      database: product-service